{% set name = "enpt" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enpt-{{ version }}.tar.gz
  sha256: 8f028f3560c63ddea21d4fdfa02538563ca422ab6d1e44e71dc659ef87e1e33f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools-git
  run:
    - arosics >=1.0.0
    - cerberus
    - geoarray >=0.9.0
    - jsmin
    - lxml
    - matplotlib-base
    - mvgavg
    - natsort
    - numpy
    - numpy-indexed
    - pandas
    - py-tools-ds >=0.14.23
    - pyproj >=2.2.0
    - python >=3.6
    - scikit-image
    - scipy
    - sensormapgeo >=0.4.0
    - sicor
    - tqdm
    - utm

test:
  imports:
    - enpt
    - enpt.execution

about:
  home: https://gitext.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/EnPT
  summary: EnMAP Processing Tool
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
