{% set name = "enpt" %}
{% set version = "0.20.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enpt-{{ version }}.tar.gz
  sha256: 15d75861cc4103c0dc1be65e68e7e24d6e81c6f862f4dcf31eb7592da9e1236d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - enpt = enpt.cli:main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-git
  run:
    - acwater >=0.3.0
    - arosics >=1.0.0
    - cerberus
    - gdal
    - geoarray >=0.15.8
    - jsmin
    - lxml
    - matplotlib-base
    - mvgavg
    - natsort
    - numpy
    - numpy-indexed
    - packaging
    - pandas
    - py-tools-ds >=0.14.25
    - pyproj >=3.4.0
    - python >=3.8
    - scikit-image
    - scipy
    - sensormapgeo >=1.0.0
    - sicor >=0.19.1
    - tqdm
    - utm

test:
  imports:
    - enpt
    - enpt.execution
  commands:
    - pip check
    - enpt --help
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/EnPT
  summary: EnMAP Processing Tool
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
