{% set name = "enpt" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/enpt-{{ version }}.tar.gz
  sha256: f4d839b6c14c206326c788a5dea43e7b9495bf13b4c21aef2545d58b82640669

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - enpt = enpt.cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - acwater >=0.3.0
    - arosics >=1.0.0
    - cerberus
    - gdal
    - geoarray >=0.15.8
    - jsmin
    - lxml
    - matplotlib-base
    - mvgavg
    - natsort
    - numpy
    - numpy-indexed
    - packaging
    - pandas
    - py-tools-ds >=0.14.25
    - pyproj >=3.4.0
    - python >={{ python_min }}
    - scikit-image
    - scipy
    - sensormapgeo >=1.0.0
    - sicor >=0.19.1
    - tqdm
    - utm
  run_constrained:
    - llvmlite <0.44  # [unix]  # https://github.com/conda-forge/llvmlite-feedstock/issues/101

test:
  imports:
    - enpt
    - enpt.execution
  commands:
    - pip check
    - enpt --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/EnPT
  summary: EnMAP Processing Tool
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
