{% set name = "enpt" %}
{% set version = "0.19.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enpt-{{ version }}.tar.gz
  sha256: f001871e4eeb15761d742c6be8eec0ec350cea4be76b4ade909d2c2f8f90987b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - enpt = enpt.cli:main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-git
  run:
    - acwater >=0.3.0
    - arosics >=1.0.0
    - cerberus
    - geoarray >=0.15.8
    - jsmin
    - lxml
    - matplotlib-base
    - mvgavg
    - natsort
    - numpy
    - numpy-indexed
    - pandas
    - packaging
    - py-tools-ds >=0.14.23
    - pyproj >=3.4.0
    - python >=3.8
    - scikit-image
    - scipy
    - sensormapgeo >=0.4.0
    - sicor >=0.16.0
    - tqdm
    - utm

test:
  imports:
    - enpt
    - enpt.execution
  commands:
    - pip check
    - enpt --help
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/EnPT
  summary: EnMAP Processing Tool
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
