{% set name = "enpt" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/enpt-{{ version }}.tar.gz
  sha256: 47a50b8e364305bc25e080ab44941f3a8b67f60ea571255ae384bc8faede85d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - enpt = enpt.cli:main

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - acwater >=0.4.1
    - arosics >=1.0.0
    - cerberus
    - gdal
    - geoarray >=0.19.2
    - isofit =3.4.3
    - jsmin
    - lxml
    - matplotlib-base
    - mvgavg
    - natsort
    - numpy >=2
    - numpy-indexed
    - packaging
    - pandas
    - py-tools-ds >=0.14.25
    - pyproj >=3.4.0
    - scikit-image
    - scipy
    - sensormapgeo >=1.0.0
    - sicor >=0.19.1
    - tqdm
    - utm
  run_constrained:
    - xarray <2025.12  # https://github.com/conda-forge/rioxarray-feedstock/pull/93 not yet merged

test:
  imports:
    - enpt
    - enpt.execution
  commands:
    - pip check
    - enpt --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz.de/EnMAP/GFZ_Tools_EnMAP_BOX/EnPT
  summary: EnMAP Processing Tool
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
