{% set name = "enpt" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/enpt-{{ version }}.tar.gz
  sha256: 895d1f9b6d8546cb72070bb050448fed49c479f09d1ccdd417b37e7ed7950b9d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - enpt = enpt.cli:main

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - acwater >=0.4.1
    - arosics >=1.0.0
    - cerberus
    - gdal
    - geoarray >=0.19.2
    - isofit =3.4.3
    - jsmin
    - lxml
    - matplotlib-base
    - mvgavg
    - natsort
    - numpy >=2
    - numpy-indexed
    - packaging
    - pandas
    - py-tools-ds >=0.14.25
    - pyproj >=3.4.0
    - scikit-image
    - scipy
    - sensormapgeo >=1.0.0
    - sicor >=0.19.1
    - tqdm
    - utm
  run_constrained:
    - xarray <2025.12  # https://github.com/conda-forge/rioxarray-feedstock/pull/93 not yet merged
    - ray-default <2.53  # https://github.com/ray-project/ray/issues/61141

test:
  imports:
    - enpt
    - enpt.execution
  commands:
    - pip check
    - enpt --help
  requires:
    - pip
    - python >={{ python_min }}

about:
  home: https://git.gfz.de/EnMAP/GFZ_Tools_EnMAP_BOX/EnPT
  summary: EnMAP Processing Tool
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
