schema_version: 1

context:
  name: enpt
  version: "1.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/enpt-${{ version }}.tar.gz
  sha256: 2d08732e57bbf5c5e56f0c21b995ddc3eab3e64b2b72f687f24cfa83b5161fea

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - enpt = enpt.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - acwater >=0.4.1
    - arosics >=1.0.0
    - cerberus
    - gdal
    - geoarray >=0.19.2
    - isofit =3.4.3
    - joblib
    - jsmin
    - lxml
    - matplotlib-base
    - mvgavg
    - natsort
    - numpy >=2
    - numpy-indexed
    - packaging
    - pandas
    - py-tools-ds >=0.14.25
    - pyproj >=3.4.0
    - scikit-image
    - scipy
    - sensormapgeo >=1.0.0
    - sicor >=0.19.1
    - tqdm
    - utm
  run_constraints:
    - eccodes !=2.42.0  # classified as suspicous by ESET on Windows
    - hygeos-core <1.3.0  # should be fixed with polymer>4.17.3
    - ray-core <2.59  # workaround for ray timeouts due to new token authentification (remove at next release)

tests:
  - python:
      imports:
        - enpt
        - enpt.execution
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - enpt --help

about:
  summary: EnMAP Processing Tool
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://git.gfz.de/EnMAP/GFZ_Tools_EnMAP_BOX/EnPT

extra:
  recipe-maintainers:
    - danschef
