conda_forge_output_validation: true
bot:
  automerge: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 8GiB
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
